services:
  kitten:
    command: python -m kitten
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
