name: Run Pytest for Kitten

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install lsb_release (needed for setup-python)
        run: apt-get update && apt-get install -y lsb-release && apt-get clean all

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run tests
        run: poetry run pytest

permissions:
  contents: read
